apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-api
  template:
    metadata:
      labels:
        app: example-api
    spec:
      containers:
      - name: example-api
        image: jstenghele/juans-fastapi-poc:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
          name: example-api-secrets
        - configMapRef:
          name: example-api-config-map
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000